[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
members = ["crates/*", "apps/mos-6502kit-gui"]
resolver = "3"

[workspace.dependencies]
derive_more = { version = "2", features = ["from", "display"] }