[package]
name = "disassembler"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
common = { path = "../common" }
types = { path = "../types" }
error = { path = "../error" }
derive_more = { workspace = true }