[package]
name = "debugger"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
common = { path = "../common" }
cpu = { path = "../cpu" }
memory = { path = "../memory" }
error = { path = "../error" }
types = { path = "../types" }
