[package]
name = "breadboard"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
cpu = { path = "../cpu" }
memory = { path = "../memory" }
error = { path = "../error" }